version: '3.9'

services:
  api:
    build:
      context: ./api
    container_name: learning_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - qdrant
      - postgres

  postgres:
    image: postgres:15
    container_name: learning_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learning_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: learning_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  pgdata:
  qdrant_data:
